version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # O la versión que necesites
    commands:
      - npm install
  build:
    commands:
      - echo "Construyendo el proyecto..."
      - npm run build 
artifacts:
  files:
    - '**/*' 
  base-directory: 'dist' 