version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # <--- Cambiamos de 18 a 20
    commands:
      - npm install
  build:
    commands:
      - echo "Construyendo proyecto Next.js..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: out 